### ISSUE TITLE
disccusion page details has 404 error

### ISSUE THREAD

**Issue by struckchure** [GDSC-BUK/sc-22.web#9]
the error is visible in the devtools

`https://sc-22-forum-service.herokuapp.com/api/v1/discussion/cussion/3a975451-1af0-43ae-a085-8b0d30e6b967/`

that url returns a 404, it should be

`https://sc-22-forum-service.herokuapp.com/api/v1/discussion/3a975451-1af0-43ae-a085-8b0d30e6b967/`

**Comment by horlakz** [comment]
I go fix this one sha, that useHIstory hook dey alright abi

**Comment by horlakz** [comment]
#10 fixed this issue
